{"time":"2025-06-05T20:48:15.5970093+08:00","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"E:\\wangli\\SFDFusion\\SFDFusion-main\\wandb\\run-20250605_204815-90xtgd4e\\logs\\debug-core.log"}
{"time":"2025-06-05T20:48:15.7037373+08:00","level":"INFO","msg":"created new stream","id":"90xtgd4e"}
{"time":"2025-06-05T20:48:15.7037373+08:00","level":"INFO","msg":"stream: started","id":"90xtgd4e"}
{"time":"2025-06-05T20:48:15.7037373+08:00","level":"INFO","msg":"writer: Do: started","stream_id":"90xtgd4e"}
{"time":"2025-06-05T20:48:15.7037373+08:00","level":"INFO","msg":"sender: started","stream_id":"90xtgd4e"}
{"time":"2025-06-05T20:48:15.7037373+08:00","level":"INFO","msg":"handler: started","stream_id":"90xtgd4e"}
{"time":"2025-06-05T20:48:36.7758034+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-05T20:49:00.0160647+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-05T20:49:25.3485157+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-05T20:49:46.4356998+08:00","level":"INFO","msg":"stream: closing","id":"90xtgd4e"}
{"time":"2025-06-05T20:49:46.4356998+08:00","level":"INFO","msg":"handler: closed","stream_id":"90xtgd4e"}
{"time":"2025-06-05T20:49:46.4356998+08:00","level":"INFO","msg":"writer: Close: closed","stream_id":"90xtgd4e"}
{"time":"2025-06-05T20:49:46.4356998+08:00","level":"ERROR","msg":"sender: upsertRun:","error":"failed to upsert bucket: api: failed sending: POST https://api.wandb.ai/graphql giving up after 4 attempt(s): context canceled"}
{"time":"2025-06-05T20:49:46.4356998+08:00","level":"INFO","msg":"sender: closed","stream_id":"90xtgd4e"}
{"time":"2025-06-05T20:49:46.4356998+08:00","level":"WARN","msg":"runwork: ignoring record after close","work":{}}
{"time":"2025-06-05T20:49:46.4356998+08:00","level":"INFO","msg":"stream: closed","id":"90xtgd4e"}
